name: mi_tianguis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/iconos_categorias/ic_comida.png
    - assets/iconos_categorias/ic_construccion.png
    - assets/iconos_categorias/ic_eventos.png
    - assets/iconos_categorias/ic_tecnologia.png
